//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataStore
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class DataProviderFactory
	{
		public virtual void GetEntitySnapshotStoreProvider()
		{
			throw new System.NotImplementedException();
		}

		public virtual void GetEntityCacheStoreProvider()
		{
			throw new System.NotImplementedException();
		}

		public virtual void GetEntityTaskResultStoreProvider()
		{
			throw new System.NotImplementedException();
		}

	}
}

