//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataStore
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class DocDBEntitySnapshotStoreProvider : EntitySnapshotStoreProvider
	{
		public virtual object AuthKey
		{
			get;
			set;
		}

		public virtual object ServerEndPoint
		{
			get;
			set;
		}

		public virtual object DatabaseId
		{
			get;
			set;
		}

		public virtual object CollectionId
		{
			get;
			set;
		}

		public virtual object ServerPort
		{
			get;
			set;
		}

	}
}

