//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataStore
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class RedisEntityTaskResultStoreProvider : EntityTaskResultStoreProvider
	{
        public override void GetOrCreateDatabaseAsync()
        {
            throw new NotImplementedException();
        }

        public override void GetOrCreateCollectionAsync()
        {
            throw new NotImplementedException();
        }

        public override void CreateEntity()
        {
            throw new NotImplementedException();
        }

        public override void ReadEntity()
        {
            throw new NotImplementedException();
        }

        public override void UpdateEntity()
        {
            throw new NotImplementedException();
        }

        public override void DeleteEntity()
        {
            throw new NotImplementedException();
        }

        public override void QueryEntities()
        {
            throw new NotImplementedException();
        }
    }
}

