//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TaskConsumerFarm
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class RobotDaemon
	{
		public virtual object TaskRobotList
		{
			get;
			set;
		}

		public virtual void Start()
		{
			throw new System.NotImplementedException();
		}

		public virtual void SyncStatus()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Stop()
		{
			throw new System.NotImplementedException();
		}

		public virtual void CreateTaskRobot()
		{
			throw new System.NotImplementedException();
		}

		public virtual void DisposeTaskRobot()
		{
			throw new System.NotImplementedException();
		}

	}
}

