//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataStore
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface INoSQLDataProvider 
	{
		void GetOrCreateDatabaseAsync();

		void GetOrCreateCollectionAsync();

		void CreateEntity();

		void ReadEntity();

		void UpdateEntity();

		void DeleteEntity();

		void QueryEntities();

	}
}

