//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataStore
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class RedisEntityCacheStoreProvider : EntityCacheStoreProvider
	{
		public virtual object ServerEndpoint
		{
			get;
			set;
		}

		public virtual object AccessKey
		{
			get;
			set;
		}

	}
}

