//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace APIWorker
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IQueryWorker 
	{
		object QuerySyntax { get;set; }

		object TaskResult { get;set; }

		void Initialize();

		IEntityTaskResult CreateTaskToBackend();

		IEntityTaskResult CheckTaskResult();

		void QueryFromCache();

	}
}

