//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace QueueManager
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class QueueTopicManager
	{
		public virtual object TopicName
		{
			get;
			set;
		}

		public virtual object ConnectionString
		{
			get;
			set;
		}

		public virtual void SendMessages()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Initialize()
		{
			throw new System.NotImplementedException();
		}

		public virtual void StartReceiveMessages()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Stop()
		{
			throw new System.NotImplementedException();
		}

	}
}

